project_id = "lxdosmjenbaugmhyfanx"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-recipe]
verify_jwt = true

[functions.check-user-activity]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.send-push]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
